
package com.sf.integration.expressservice.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CommonExpressServiceService", targetNamespace = "http://service.expressservice.integration.sf.com/", wsdlLocation = "http://bsp-oisp.sf-express.com/bsp-oisp/ws/sfexpressService?wsdl")
public class CommonExpressServiceService
    extends Service
{

    private final static URL COMMONEXPRESSSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sf.integration.expressservice.service.CommonExpressServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sf.integration.expressservice.service.CommonExpressServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://bsp-oisp.sf-express.com/bsp-oisp/ws/sfexpressService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://bsp-oisp.sf-express.com/bsp-oisp/ws/sfexpressService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COMMONEXPRESSSERVICESERVICE_WSDL_LOCATION = url;
    }

    public CommonExpressServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonExpressServiceService() {
        super(COMMONEXPRESSSERVICESERVICE_WSDL_LOCATION, new QName("http://service.expressservice.integration.sf.com/", "CommonExpressServiceService"));
    }

    /**
     *
     * @return
     *     returns IExpressService
     */
    @WebEndpoint(name = "CommonExpressServicePort")
    public IExpressService getCommonExpressServicePort() {
        return super.getPort(new QName("http://service.expressservice.integration.sf.com/", "CommonExpressServicePort"), IExpressService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IExpressService
     */
    @WebEndpoint(name = "CommonExpressServicePort")
    public IExpressService getCommonExpressServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.expressservice.integration.sf.com/", "CommonExpressServicePort"), IExpressService.class, features);
    }

}
