
package com.sf.integration.expressservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IExpressService", targetNamespace = "http://service.expressservice.integration.sf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IExpressService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sfexpressService", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "com.sf.integration.expressservice.SfexpressService")
    @ResponseWrapper(localName = "sfexpressServiceResponse", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "com.sf.integration.expressservice.SfexpressServiceResponse")
    public String sfexpressService(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

}
